# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo/vulnerability-goapp
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            go get -u -v -f all
            go mod vendor
      - persist_to_workspace:
          root: ..
          paths:
            - vulnerability-goapp
  veracode_sast:
    # use a java-based image to run the Veracode API wrapper
    docker:
      - image: cimg/openjdk:8.0.282-node
    working_directory: ~/repo
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: .   
      # grab the Veracode agent
      - run: 
          name: "Package for upload to Veracode"
          #command: zip -r upload.zip nodegoat
          command: zip -r upload.zip vulnerability-goapp -x *runenv/*
      - run:
          name: "Get the Veracode agent"
          command: |
            wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.2.7.4/vosp-api-wrappers-java-21.2.7.4.jar
      - run:
          name: "Upload to Veracode"
          command: java -jar veracode-wrapper.jar 
              -vid $TEAM_ANALYSISCENTER_ID
              -vkey $TEAM_ANALYSISCENTER_KEY
              -action uploadandscan 
              -appname "goapp_CircleCi"
              -createprofile true 
              -version CircleCI-$CIRCLE_BUILD_NUM 
              -filepath upload.zip
  
  Veracode_sca:
    docker:
      - image: cimg/openjdk:8.0.282-node
    working_directory: ~/repo
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: .
      # download and run Veracode SCA
      - run:
          name: "Veracode Software Composition Analysis"
          command: |
            cd nodegoat
            export SRCCLR_SCM_TOKEN=$github_api
            export SRCCLR_SCM_TYPE=GITHUB
            #export DEBUG=1
            git config --global user.email "$emailgit"
            git config --global user.name "$nomegit"            
            git remote set-url origin https://github.com/VictorM3/Vulnerability-goapp.git
            git checkout -f master
            export EXTRA_ARGS='--update-advisor --pull-request'
            curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan $EXTRA_ARGS            
 
workflows:
  version: 2.1
  build_and_scan:
    jobs:
      - build
      - veracode_sast:
          requires:
            - build
